version: '3'
services:
  c3pv2server:
    build: .
    image: c3pv2server
    hostname: c3pv2server
    container_name: c3pv2server
    tty: true
    privileged: true
    volumes:
      - ./log/:/var/log/
      - ./home/:/home/
      - ./git/:/git/
    ports:
      - "22000:22"