version: '3'
services:
  c3pv2server:
    build: .
    image: c3pv2server
    hostname: c3pv2server
    container_name: c3pv2server
    tty: true
    privileged: true
    volumes:
      - ~/c3pv2server/log/:/var/log/
      - ~/c3pv2server/home/:/home/
      - ~/c3pv2server/git/:/git/
    ports:
      - "22000:22"