version: '3'
services:
  centos6ssh:
    build: .
    image: centos6ssh
    hostname: centos6ssh
    container_name: centos6ssh
    tty: true
    volumes:
      - /root/centos6ssh/log/:/var/log/
      - /root/centos6ssh/home/:/home/
      - /root/centos6ssh/git/:/git/
    ports:
      - "22001:22"
